force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/ClassSubject__c.field-meta.xml
<CustomField>
    <fullName>ClassSubject__c</fullName>
    <label>Class Subject</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>History</fullName>
            </value>
            <value>
                <fullName>Math</fullName>
            </value>
            <value>
                <fullName>Science</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/ClassTopic__c.field-meta.xml
<CustomField>
    <fullName>ClassTopic__c</fullName>
    <label>Class Topic</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ClassSubject__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ClassTopic</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/PageExtension.cls
public class PageExtension {
    
    ApexPages.StandardSetController setController {get;set;}
    
    public List<Class__c> classlist {
        get {
            return setController.getRecords();
        }
        set;
        
    }
    
    public PageExtension (ApexPages.StandardSetController controller) {
        setController = new ApexPages.StandardSetController([SELECT Name, ClassSubject__c, ClassTopic__c FROM Class__c WHERE ClassSubject__c = 'Math']);
        setController.setPageSize(5);
    }
    
}