force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/ClassSubject__c.field-meta.xml
<CustomField>
    <fullName>ClassSubject__c</fullName>
    <label>Class Subject</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>History</fullName>
            </value>
            <value>
                <fullName>Math</fullName>
            </value>
            <value>
                <fullName>Science</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Students Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Graduated</fullName>
            </value>
            <value>
                <fullName>Prospective</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expelled</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SelectQueries.cls
public class SelectQueries {
    
    public static List<Account> getAllAccounts () {
        
        List<Account> accountList = new List<Account>();
        
        accountList = [SELECT Id FROM Account];
        
        return accountList;
    }
    
    public static List<Contact> getAllContacts() {
        return [SELECT Id FROM Contact];
    }
    
    // get all Accounts where name = GenePoint
    public static List<Account> getGenePointAccounts(){
        return [SELECT Id, Name From Account WHERE Name = 'GenePoint'];
    }
    
    public static List<Account> getAccountsWithName(String argName){
        return [SELECT Id, Name From Account WHERE Name = :argName];
    }
    
	public static List<Student__c> getStudentsEnrolled(){
        return [SELECT Name, Status__c From Student__c WHERE Status__c = 'Enrolled'];
    }
    
  	public static List<Student__c> getStudentsWithGivenStatus(String argStatus){
        return [SELECT Name, Status__c From Student__c WHERE Status__c = :argStatus];
    }
    
    public static List<Account> getFirstFiveAccountsWithMoreThan100Empoyees(){
        return [SELECT 
                	Name, NumberOfEmployees 
                FROM 
                	Account 
                WHERE 
                	NumberOfEmployees> 100
                ORDER BY
                	Id DESC
                LIMIT 
               		5
               ];
    }
    
//    aggregate stuff

    // relationships
    public static List<ClassEnrollment__c> getMathCE() {
        return [SELECT Name, Class__r.ClassSubject__c FROM ClassEnrollment__C WHERE Class__r.ClassSubject__c = 'MATH'];
    }
    
    public static List <Account> getAccountsAndTheirContacts(){
        return [select name, (select name from contacts) from account];
    }
    
   	public static List<ClassEnrollment__c> getAllEnrollmentsForGivenStudent (String argStudentName) {
        return [SELECT Id FROM ClassEnrollment__c WHERE Student__r.name = :argStudentName];
    }
    
    
    
    
    
    

}